POST http://localhost:3000/api/equipos HTTP/1.1
Content-Type: application/json

{
    "nombre": "Compresor",
    "descripcion":"Máquina de fluido que está construida para aumentar la presión y desplazar cierto tipo de fluidos",
    "serial":"Khote15341",
    "fechaInTr":"2017-08-15",
    "fechaUlTr":"2021-06-25",
    "fechaUlMt":"2021-06-20",
    "id": "4"
}

###
PUT http://localhost:3000/api/equipos/3 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Ventilador",
    "descripcion":"Produce una corriente de aire de mas de 100ºC",
    "serial":"ls0270ft",
    "fechaInTr":"2021-07-21",
    "fechaUlTr":"2022-10-12",
    "fechaUlMt":"2022-10-05",
    "id": "3"
}

###
DELETE  http://localhost:3000/api/equipos/2 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/api/trabajos HTTP/1.1
Content-Type: application/json

{
    "id": "7",
    "fechaPlMt":"2021-10-07",
    "fechaInMt":"2021-10-07",
    "fechaFinMt":"2021-11-07",
    "estatus": "Finalizadoo",
    "tipoTrab": "preventivo",
    "idEquipo": "ls0270ft"
}

###
PUT  http://localhost:3000/api/trabajos/3 HTTP/1.1
Content-Type: application/json

{
    "id": "3",
    "fechaPlMt":"2021-10-07",
    "fechaInMt":"2021-10-07",
    "fechaFinMt":"2021-11-07",
    "estatus": "Finalizadoo",
    "tipoTrab": "correctivo",
    "idEquipo": "ls0270ft"
}

###
DELETE  http://localhost:3000/api/trabajos/2 HTTP/1.1
Content-Type: application/json